language: python
python: 2.7

env:
    - TOX_ENV=pyflakes
    - TOX_ENV=docs
    - TOX_ENV=py26
    - TOX_ENV=py27

install:
    - pip install tox

script: tox -e $TOX_ENV

notifications:
    email: false
