language: python
python: 
    - 2.7
    - pypy
    - 3.2
    - pypy3

env:
    - TOX_ENV=py26
    - TOX_ENV=py27

install:

    if [[ "${TOX_ENV}" == "pypy"* ]]; then
        sudo add-apt-repository -y ppa:pypy/ppa
        sudo apt-get -y update
        sudo apt-get install -y pypy pypy-dev

        sudo rm -rf /usr/local/pypy/bin
    fi
    - pip install tox

script: tox -e $TOX_ENV

notifications:
    email: false
