language: python
python:
- '2.7'
install:
- git fetch --tags
- export GIT_TAG=$(git describe --tags | cut -c 2-5)-$TRAVIS_BUILD_NUMBER
- echo $GIT_TAG
- python setup.py install
script: py.test 
after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag $GIT_TAG -a -m "Generated tag for build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG
notifications:
  email: true
